language: node_js
sudo: false
node_js:
  - '4.3'
  - '5.11'
  - '6.2'
cache:
  directories:
  - $(npm root -g)
  - node_modules
  - $(npm config get prefix)/bin
notifications:
  email:
  - devs-deep@mitocgroup.com
  slack:
    secure: CParjUyPwAK8/GB/OUmSjzfDFzls9F05h5+vxjpkvuFRmCpqbJKwEA4M9KRR+VK+H9nGJcUzTJBFLNTsADh8+hmKDt5vDsCxZ48hQ2zUIJfMIXVtpf/Hxs3K1HfLhN/YCkO14o1MMMkmXFqrbPI8YqmupdlXBVG3YQM1N0B37vnlsjhcEtJgql8FUx1T5CtFuNjRzA5SqYhx7/G1O/xtAYKkYfD/XGyoJBZngMfQ/FY/6fUlBztedC8n6RgcrzDi0phIWmT1u0naVgK8CI9ywa2/Cn0sozTfZQA0TshlDjM6aZdBqd5rxWZKm6faCzr36mmtr0eowHt6LuhGKR/RNx/Q9LDiCleOGOv6l+qbjIqUB4WVMMec7t6V0cENeWgUPYLhUZ7Z3/HKRO4jdbeSpMc8mpJ7BxW1kCWgtYqOP/yRRfXuBC5wxybFkI3Ljv63YVMCPmL8qHcidiLsa1adr4nBuBkrV/A67BUzonhdSVOuvS/sxVxy187xwHsQITBuf2gL+oRCzBg8K/dp6O0M3xkvGsXDoUa43B85kgOEJ9YoAqnuf0Q0iuDSgu4YaCnZHSoKF+dYmy+M5fQTXSzYm9Mk9rfAA/lES/2iWJcGOqUQlpoG3y7BhJhX8X0+zWPrIzPiECMMY38bnRsxr6rxY39Zih/X6mjoph3amyru1fs=
branches:
  only:
  - master
  - stage
  - test
  - dev
env:
  global:
  # Disable interactive user mode ###
  - DEEP_NO_INTERACTION=1
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: O6JOHRkqqfGL023TwFSbhuIK3iawXs/QbAcb1C60YYqkavpbMKCCW/mBWUx1rfXzmBRErhD+dPgJYrEwmaxCAB1BbHSKfJXXMnYaqVgrXrpXFOaOUoNBCPG9TaUmoFZbY0+ka0c3iGJGYNDvzgj4rdY4HnF5IVbiiP0IqSQiDz0UXbupHExcIZElQqcg3J6+J/lXA46MR2TPXqRLJUjrbtfU6lmluqkEo4vfHCReKvHSQ/z9HuM8KVx2ObbZMq5op7yrPakGIokmA6St0pmAVLxRqgZQeHw0B5BEVPskgUByfDhlfrJ18RRej8BJFrczsLOkvgqaxL+f1+MgaObINIU/WdpF7qf9lAV10WsQsLUsO1hOo1uQpEDn1ELmGX+NxhEfJB8Sua/erGwZQl/vD2oMRuoEF5TtM+izaEaBU4bbOKYt8Z974SqXJ2rz7m15y2RYT357DpSZv/CaN1k0h1LO2Heogi/DFoVqI69bdPVAsZrFDxT3CYKZN0Os9Y9wLc9PMtJjtLNFewSaIAhFyM/s2FwgrWQa9ZX/gGZnDshAXiKLzo1etVvuE2sm8sD6eHFiAjLSt9ah9YoMSyVbRwArA0gR4w6CqDyNxKGPEkNUim1Dzr6+pgxoY9jx7w53Luho/jKHtOapRlg3mBHc3xaL1X76tW4f0o1bA5VYbFE=
before_install:
  - (npm list -g babel-cli --depth=0 || npm install -g babel-cli@6.x.x)
  - (npm list -g browserify --depth=0 || npm install -g browserify@11.2.x)
  - (npm list -g mocha --depth=0 || npm install -g mocha@2.4.x)
  - (npm list -g istanbul@^1.0.0-alpha --depth=0 || npm install -g istanbul@^1.0.0-alpha)
  - (npm list -g codacy-coverage --depth=0 || npm install -g codacy-coverage@1.1.x)
  - cp test/package.json .
after_success:
  - npm run coverage
