language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
  - "$(npm root -g)"

branches:
  only:
  - master
  - stage
  - test
  - dev

env:
  global:
  - secure: "XRyiCh1Y8FYnusN92mjVR3dcBWRJBc6Dnw7FDHxdp1c9Q2FUA4WXPzp9R/vjarPIoZ8mVPki2ifV08oaKddyl8FkJKKfLXDn0JpquSKcYdQn6vJqoj050tpNtLsR2bBiLuTf0pH2IzST9KES4NooDiJEVhzcjy8dwm+adKSg3WGXO1WRWkG3yy+ujfiiz8aEIMnZmb2MTFtAUoCdAZv0u1DHYJP47jppzSHxvjVG10zecDF0fEUlE2tnkDWB8FoifVe56PHEGtJ/fQq60elQEYFBb35bOlrFybZrXUw0q+Iy4Ssrljn9EDXO+kd75XTEMCchioGsuMabFdaqR+5sWuilHadsQTTGdqGtz1zKC7FVChsfe1+J/pxqpBDiE6LldeTV5ROsk+7oBSQBHM7kHemUlR1pc9/TbnbiwiIojEG+XlBMLGFD61OBB6pKzTZPuBvFv5myGk1grYvWboWvQ9hjMlO1PnAlaXQ52TolcisPXKu9qGHHVNqdz4c6RFSZugAhTnfEn0bk68PKWUZCRFpfZhzzBOl8gKAySOgf5y9bFN8kR+sb7UjfS4VFESSz7jxqP7QUKV7qvYgSViHAnyXCJANBdoS9oTjucSWHJZZHnWF42HV9WHzMco9pd7x5bMjJB95rLRzS4Nk3Sn7M6yimE0Uah5WOt16hVUgw+oE="
  - secure: "xclYD6G2Qs1JwbGICM56aVpGzk3Y0tB8RspermtJchqPJOtFH5+HpsuUKGWedN9F9tzwfAeLW3JeSgagoOp55vjWOIk1qmj7bWCZy5wz2ccTDwSNm99joUevf4tEoGZjrUmvko5/wppOdUw04+LqwQ8oAI1sj2z2iJ4BLz1LTMgSOm05hCObsajSySq5QiphUg6Ueyw+yEKDYbZsxVdsQStV2yMpNPBloSsY5hB8hgzROjJthoPtYHEBS6oT4P/FFrrJuqHB8O94bbQy8oXpdZ6idGbtB9ngQI4AiY77Yu2Vr6yEhnznSTzgBZGSEoYNx3GuhFESgFPGlLiDLPG7gaO13bR4moI4gGsRhawY+zmlaK1P7Sd5bCSb7uS4rGg1TeTDF7PWobmOx1eHM5fRxR4T7GNS3Pa3lod1MAPemJGtVHCD41xqF35jvTjPvoBInknMQZg9mV3llD9eNTl59NAbiYBANd0hGns6J6cYIWqSgAkhFNkK2DblkPBytnIWazaKoELNPhu1jlCZ/wOItaPZAyRo2ENA87hxs2Rxjp3FbeW7QcRcBPf3QIxZLO8vkt1NgSl2+Wz2tvWFKQjNCeinpdh8jiEx3apdWWwZW95o0U7lKJhcg4p3dyk8LsRi2cNLTi7+RtbAGW55HnSXuhmzIzZEmCDf/rZmERoJekM="
  - secure: "rUEqx7/9cFUuC1DnF8isvtmqf0RcOFoXULkW6g0bSb3X6HeLcc1ZhKRQp0iUTKbi6j8ZD1iAurmyUcrLExUkjvCpD5fQQ2c8IkEiEKkqnIkeccV0mKaYuwC7mr1sUMLeN4U92qKTLsZ3yXVp44SWlfzltTfrUOfiZaw2efFW8WGBiltxCp0n3pZ10F3Eo3NVkrlig1Q2d72w8GgaUoVk+k4hmvHbIfP9sLUkEf0xCALcMvi2Wupx6JqI7mxC8iG2vU1XnIUi9zTIeSpnd8tJJnOfP7dofwoa6RXPnQzcy0r+/Bu/2WMI8GmDd6EFB4v7qyAQOwVtaQIXm0A21n517A5yNuLE0/be6QNY+dfITAeDTcFB5YPGWyULpr2qYL85jSpyZeah25dRCDoE4JTbz/GT6TUk3YPnBe/VY6iELrCIQPgZt5+ZM8vApxfgO3D5U+eH4FSH/B+jEq5Xni+depU+PS1jSA9aaiMK5udaTqh1jZB5KRqrEXhvEwDLHvcVGgCW9GuMlxd4OsXOtnlZdbKQHoVnTqJ8/sxubSeYFqclPwNVFitFPy8VtCZBX3GaLlWns9NCUHLQDzt121CE2F3E6gFtQdTCRhf/k9+kICuY+Qi+3JiclJyIS1QKgcRTHmLkLrqfA8KzpjlpWWzPYxMCaQ8WQjWT+lS9+XbeeDY="

before_install:
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- cp test/package.json .
- test/bin/setup_npm.sh

after_success:
- npm run coverage

