language: node_js
sudo: false
node_js:
  - '0.12'
  - '4.2'
  - '5.3'
cache:
  directories:
  - $(npm root -g)
  - node_modules
#notifications:
#  email:
#  - devs-deep@mitocgroup.com
branches:
  only:
  - master
  - stage
  - test
  - dev
  - coverage_update
env:
  global:
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: wbln/M3Na9lVEmIpFbo9IWsrCoTOH1uhfGxHQXrILoHiRwL7BthoY3ajZhHePCB0hiG5VdhnwmqTcnSByv2saXiFTM8v29Jv43wzIU+hY7DWCL5r4VyEuzyXTAopAJ5+ASY83Ys+5ztGanXXlQH03HwsM6t3hVm3hnUtef4JzY1WhL7/nya7IEtiprw+L7mRyJ8NSV9iPH4abuMvYQ5SPxJDmfMjlmkH4XhiV6EYnQ96L7LTvpph6BRs15m5pf3UChfXRqVHgGd4JlIdYvaSbPvcZ+A11FyRn5ptreLGs9sW/9hUasC44IUodcyaHY9Krn/w6j9RJH7EkK5mO61FB84P37+xcppf47n+p3gSisVKcJfFyDu7JK9JnAun+1AK1gi8Ck1WzxWTsBAhIDCVxI60naSIu6Wy+R9Jj+th7XOEN9sOEAgzYbaQoS74/F3ZjS8kqTmDK/XD5Ayph/fR5RTOoMbBF99ausR6MzgmuL+Ednqyp23ZMzDFnOdzoJ74xF4d9kY3llVja0hMIY4n1jwa3rHZStUdJNsxCJPeNe2RMs4ZXzcKKRg3PlsHldSUuIvt+gGY9+LJnNcxZ1YyOfccMvSrAlExs+0ZDVTO1WYWsUgbpU5puw18wfO34lfEsgVsI6yXc2wylciA3NK881/6Vonv/8TgobOI7EwhzF0=
before_install:
  - npm install -g babel@5.8.19
  - npm install -g browserify@11.2.0
  - npm install -g mocha@2.3.3
  - npm install -g mocha-babel@3.0.0
  - npm install -g istanbul@0.3.21
  - npm install -g isparta@3.1.0
  - npm install -g codacy-coverage@1.1.3
  - cp test/package.json .
after_success:
  - npm run coverage
