language: node_js
sudo: required
git:
  depth: 1
cache:
  bundler: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # AWS_ACCOUNT_ID=[secure]
    - secure: "Cu0f6cUkQLLCYn917A5S4F7HnRr/Czyoaa0OnV2HeDzehHakELHPt4NOmxQTG7ZVwbxrqLvPOskV1XL/mAXKMJIL+1xwpy5M8Imx8pBM0XCAvnqrPz6kRsTJSyEml+4L/ZGuglq6+eNP5ZQCNe8IBwvvj2A93bxfY+KjcI4eEqddKHbDXCXeoGifnEiR1fwbutmPnNZSwDHOGspuDu0qnWMa9Q7oTIFccdwUtalBAEiH58GLta/LPlVnw5698md6CE2lhXzzz9SMLBIsoQVsyIA4B7mNBhI7rkP437qJ+37klnOUOdSvksMPTioZ8j1GVTm4JApeof66wPXIX3oONJTenGqBNk53+hrBrlEurBTg/j9flcMdmt+cyF7n37aYUkuxvGePfVYdmag0+UZsy37F23AZUpT8hbUq8moI/rfxox5557xaSgw4iKpqgHBKNAzztcRkh66dW1gBPutFKrfzwwbrtDZg/BbH8fDZEi+PfhUlrtUYUyt4IjkjbrxDS7z80YdCWkMECwed3LXwHS/xs2RG4OVQd0hXndJhKfi2JVySausO4Mz8DRd3FhxykGqgy9qcN5hTYQL7ZALIG4S5zsqwnxyykvJJzcXQTZx5ZJ0e0jg1SKnMOobyfCUZ1fGV2E7ghrgznA3Rf7EkYAAAVAOQLNMKIeX+D8oTRoA="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "SWdr9llbwNm94RVR74hyoDvDnsbXg6wVbklXESBOVtuPOGjwgOYkQbhSvqVVxOaVAZo7bxShe3koGAUngivxnoUxU6+Sd9ezZfjhDfYcX61/VnqDBAAZRyBfMWZBh7qa2fuLTpV4f+Mls6XdkyA7Sh4GoVkFYgtVi0YwyE2ZT/NZUDnFflDsehN/bV77T3Z6WaOFdCPqG1OL2zszu2bWON1xVOOowgn51xDgnScFv0zYf2KVRpZseYkbR5gRX5pl+7EeWsMndelhWgBfthRN37ettS9pOfXiqksy6yzAIxqo9xQ/BIcpBuxyZBKppw2mZdltUl4rwzWtcXjQF/kn01qGzktpYn3Oqtnl9OQQh5YVHrum9/CUp3LO3IZe9yRh9Eeydp1StE/cLe4QfO5Aq0q7hWShw0/wJnBwfBS1qSlHqnNSwCKxvht8zEup/9kR1qqFALJMZOE69ns/cGwnR8xoH+mtFohlKAjsjOa5K86izFAs+jwXC3moxdkrnp2X1113IwLfCh+0H+aVV1zDPkzz9gTzaGwt7TZXVixYZKssZ4GLb6H8g8qiCPWkail/7Uij33W5eIUneql2bn0NuQJGd0N9zhmnArxGZy76x+ORELqBT80a3a5hWpf8YFR7dwuAAHTO3Xxiv8il5RVU5CpQypa0bs7uzp5Nu/aAiRE="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "OvaFbK3IT6+HukNLubTf/f1/sbyX23oH3ezyrfGZMgyyOEjtOZsSP2yWZf9X2h2fGcUKNbYoubYxjDcE5sqJnTlMVUzvLVxnQBLkdSVwkOgD0vJsWbQKm/UUOk50gfSVHaDyi9Yf0Ivmg0XJE+nPDD1ufHHhNZNXJnf5T/qBqOujJ+ny0HYn38+gOI728R4yAoda0j6l6visTOhUGti7p3amvtVd1DSIwbm256Ul5guAPzidZCzllnRrBKpevXapxNUhLmHTSvjTFRkOAcWO68LzmFfoIIxQC+kRcUWshyPTjik2+n3AwtbNoFOHTRITrKzMj1mqTRswh0cKZqQX7SGvgr747iuSzMKQ6tUXm9L7Yoo+hpx+jii7rLgDWzBDUlF4gxWNAf+tHeN+0NpOY0jMNNXhMq6ckY7F8v5ZeyjbYvOF//ernmvGvG2CzNrCBVqiXxqOMk24dcnepQZMD/M4RT/4Sa4mV3dhp2GS0Pu9WLfH7t7Mz/HK/2VhI6ky4JtzhweSgKIEiIW/y8Rn76gCI9hrgBXVsgQbFz4I1oO2Ll8LyerjvPpfPC/LXrrnwlBEPJHZWG551yA1fTXWNG9TfUC0ucT7PjrKRVGZIZCG+ED1QK7qoGrKQhuQ4BxUsjLdN1g5+qHsxpx336eIcxOAi3Mq9IuFzeJwi5sbgx0="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "cm9q8Oz5PEtG1ZKvEYhEApfK1Mrtskw4T3R/qjZCg14UZuYAUHgdJhvuWPjisccdTc78UwZgnC7zZBJkkqfXT0JZwVVlGfacMB2nzot+y0fhQXM+QOxgy+qOmy3VhYcSYBNrjdZGSi7LbyGUTDirYcXe0AdZbfCL6vh4XAHzL7xJI25w2sD74xCjenjUFNig/uDMuq+kPQ3L770H7+oXHh7shVhPPXwMWA/9fJ8nODV81H3tTGjdzpUY1Wl7pX1BQ/0JWP/CiLGb1BxINHSF2TRGlXRb9dzjIGjaRupcSzdRWDVNGWH9p3Y27YegDJPXiCJO3ElBKDTGxjokkzWOc+qSgVAoukw4uMW9yVciVO4r/aq8GpRMyO/rZyflyg0UfIOuJksyPYV4zFzp3xtCHUiy9NCxURAMo0tN1RAJToOR6Ab4PkBMEn/dsiIGjYDda5SF0hU4ievr2ZkGjPVN/0zNiafWssPzj3dY2WOwAPSDq+vcpJIt396AILedxPCnz+iKS8IJB2+4RJBvE4daM8EnYa7JlaF2j3FSc+egKmTRxCpo+cm6282GqomujtG8f3unDFnO21lhGdyVc/MEH+XmdsKeXb7JSXH4niqePyoXycBk3yCHOPo1yhuhVRa8a3NXD4qTNV3MvmD+9Lx1JJj8XKG21nkAIDdQL70iMfA="
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "0UnCYOZKZko82ZNIZYfapAfsPbXFJnGbHmbe1KiPTf8Y76ZQz45XhHbVm3xO0QXbAkon3ZPdm6GiYOvjirW1ilc+qekDmiQKG46BSOnkSnAp+OJanpKRao7l6Xxc+nMSLHrg//5qWNYGHUg6P5NouGXRR1NfwO+UlR5L4HPZqpp95Djx3Mb61dn/kniDjdEmXrPBKJ8M9W/qEp8Zzik2WLq7B06yLTYH6U/S1sNPFiKJ8wV880l/EzrBg9/w5ZO6ngbvMu/NIcXCylRPGb7eFLtEI6mBD+8BNPoI5SKH6Suti9pxHzYH8hliT2ih811JD8RWCnHz11q+MS2zU3ihVsrAeIOmxIrULqo1lCpxyGxv0xNN610O03W6K0vgxkgCO+lprhLNEBBmcGZk6ygIkxnHFm1bnC2S+xly//1YAKcwWxtHOU79MWtQkCt7vYq9xRSx0Ck8OhnZVKr/2g2neHMOPv1kYwYYXza+lt+sjgMVYakX4MAhkFoH8xPTeBrs/ZanfYPmA/trZwSah/X0wDp43tPamulEy7hK9HqC2pWcNvCXr5lOJhG4hHIOIr3H3rnXR0P6tLFI4tmdnyhqJbYFWMDjyCzZfU/eRGko9LSMWTqJ5arN5BC5/sEY10uUN7hcZAzmAkz++KvAdUR48YvLd7/8rbrKGQS/tHJ1S2A="
    # SNYK_API_TOKEN=[secure]
    - secure: "VJmmYNRsFZRDxIxuwrzvRU8ImSQsWaCxBkZvW/WbDtjJbk6AXKvcIi3phBoIcY5jLVW1hlXDA6Ixf0mFspqSYl04ROSAXI1Quog2L3KY9p5twWKzbXDnlsnxabBfGLht+5BsYaBj7gfQczemW70rRh3juBk9FplTiQ8nrXg4azCDoGCTEFnXMIn6S0fE/7SrLyVILt+Fo9NH5JdUExozb5xqrY6Yc7bs2VB5IrbwOP8IwYJ9iuC1i5atScIvwJ0tnfI8UGlp7hlFoz6z5VEAY7JVG5/qooS5HP4XxGtaMOyp3ec1CgdM6bGfTHritMmMfnSsySwipth+LmYznM2S1ABvZQIyqDoSR7GuDD9FgFP/ZUi44QZ+PdSJMCRDqdH+xJ4r48nYdgDsKyU4AjC5+y5m3qIAQ82LC/bv7CyZ8XdDF4/VmR6NRWCDGvDUnW9rWU05Bv98i6VRTde4KEt6xJKoPTFg+qU2NY6Lhb3NFWj14ICtX3KC9FlH99amyJ2UhrQNoBCQnIi+lWlhHx9uS7HbzXjs9aL3ScGeEmiQk5PUI1EbcgdX3GzFh0iIwi9zfsF+81DwQGXwFOlDFIg6j6TYTmdTnpdIEaPrDJ9yiqthv5S2LEeMueMZSStHp8NlriNe4zQJ/YqeIku+ZLlykpANTpxwaZRfz/FW3I4sTAE="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - npm install -g recink
  - npm install -g recink-codeclimate
  - npm install -g recink-snyk
script:
  - recink run unit -c recink-codeclimate -c recink-snyk