language: node_js
git: {depth: 1}
node_js: [6, 7, 8]
cache:
  bundler: true
  directories: [node_modules, $(npm root -g), $(npm config get prefix)/bin]
branches:
  only: [master, dev, stage, test]
before_install: [npm install -g run-jst]
script: jst run unit
env:
  global:
  - {secure: Q1G82Et+V54aASh2dR2W1mqyQ7nsej1LFnK69mg5KslFJ0rRJ7PknIn7iNYUhJGMuKCQWBVeTxRY5YUmpGVdg+DqAKq77O08+PtrUG1/zZL+30lVE/t0I7WaiyLqqNHnuH2AcSG7DCe0/hIEcKBjWomFBqX+qxCdS2ik4Lpdf6KkS4wlCewSEhtLa0yJGW1Q1M9NRQZgP5O34zeCnR42fj4AKmrxAkSQCwGpKmjLhTeaNyYeHa5i21Nrf8fiRBX+5wUltr0UfuZ2FyZ2wVxoJ3EMrP8fkYvs4QMhvrXaUi4LIt58ZgCNZjxrATaDWxhGLZq+BVvFDxJCTcL+BAqSPKP4ShefNiNnz0Soj9AQOyITuRZ8uW0gu9oYdpkdGvKyyoqGnPdow0fCs/WaiuQZaRYVWziQ2o6CMNGZWUMto1zkyUBDz89KrqESC2X2EKuFnstx9oHRKkRlNeKYPqnX2c7uI3Rxq8B7FJGLzgheHCYtHjV9G1R0hzN8lfzcO2cyRJx8AxAFR0O5wcYr3rHAhV0BdiDZGJhyW8PpD/jE9wybZ78YeLAgppqq8rxvgOJskEu7692Hy6EPxC4jGENldtilzBHXgBfTuLw64AwPPyLKibeJJdRwQ5JagpQTrl/jwry4ln8Xd3kZgnu0uJEZA4rZK48NlN9w/cQ4c2F7yAk=}
